version = 0.1
[prod.deploy.parameters]
stack_name = "alvaro8317-portfolio"
resolve_s3 = true
s3_prefix = "alvaro8317-portfolio"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
