on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies (frontend)
        run: npm ci && npm run build && aws s3 cp dist s3://alvaro8317.lat/ --recursive
        working-directory: src
      
      - name: Deploy app (frontend)
        run: aws s3 cp dist s3://alvaro8317.lat/ --recursive
        working-directory: src